set shell := ["/usr/bin/env", "bash", "-uc"]
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]
# To load .env files uncomment this line:
# set dotenv-load

# default command
default: help

# render SVG from markdown
build-svg-docs:
  @docs/svg_gen.sh

# 🤔 Show help messages for targets
help:
  @just --list
